spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
server:
  port: 80
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS